'use server';

/**
 * @fileOverview AI-powered salary slip generation with adjustment explanations.
 *
 * - generateSalarySlipWithExplanation - A function to generate salary slips with AI-generated explanations for adjustments.
 * - SalarySlipInput - The input type for the generateSalarySlipWithExplanation function.
 * - SalarySlipOutput - The return type for the generateSalarySlipWithExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SalarySlipInputSchema = z.object({
  employeeDetails: z.object({
    employeeId: z.string().describe('The employee ID.'),
    fullName: z.string().describe('The full name of the employee.'),
    email: z.string().email().describe('The email address of the employee.'),
    department: z.string().describe('The department the employee belongs to.'),
    team: z.string().describe('The team the employee belongs to.'),
    dateOfJoining: z.string().describe('The date the employee joined the company (YYYY-MM-DD).'),
  }).describe('Details of the employee.'),
  salaryMonth: z.string().describe('The month for which the salary slip is generated (YYYY-MM).'),
  grossSalary: z.number().describe('The gross salary for the month.'),
  advanceDeduction: z.number().describe('The amount deducted as advance salary repayment.'),
  netPayableSalary: z.number().describe('The final payable salary after deductions.'),
  companyName: z.string().describe('The name of the company.'),
  companyLogoUrl: z.string().url().describe('URL of the company logo.'),
});
export type SalarySlipInput = z.infer<typeof SalarySlipInputSchema>;

const SalarySlipOutputSchema = z.object({
  salarySlipContent: z.string().describe('The content of the salary slip, including adjustment explanations.'),
});
export type SalarySlipOutput = z.infer<typeof SalarySlipOutputSchema>;

export async function generateSalarySlipWithExplanation(input: SalarySlipInput): Promise<SalarySlipOutput> {
  return salarySlipWithExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'salarySlipWithExplanationPrompt',
  input: {schema: SalarySlipInputSchema},
  output: {schema: SalarySlipOutputSchema},
  prompt: `You are an AI assistant specializing in generating human-readable explanations for salary adjustments on employee salary slips.

  Based on the provided employee details, salary information, and any deductions, create a professional and clear salary slip content.  If there are adjustments to the salary (e.g., advance deduction), provide a concise explanation for each adjustment so that the employee clearly understands why their final salary differs from their base salary.  Make sure to indicate that this slip was generated by Arogya Bio.

  Company Name: {{{companyName}}}
  Company Logo URL: {{{companyLogoUrl}}}

  Employee Details:
  - Employee ID: {{{employeeDetails.employeeId}}}
  - Full Name: {{{employeeDetails.fullName}}}
  - Email: {{{employeeDetails.email}}}
  - Department: {{{employeeDetails.department}}}
  - Team: {{{employeeDetails.team}}}
  - Date of Joining: {{{employeeDetails.dateOfJoining}}}

  Salary Month: {{{salaryMonth}}}
  Gross Salary: {{{grossSalary}}}
  Advance Deduction: {{{advanceDeduction}}}
  Net Payable Salary: {{{netPayableSalary}}}

  Salary Slip Content:
  `,
});

const salarySlipWithExplanationFlow = ai.defineFlow(
  {
    name: 'salarySlipWithExplanationFlow',
    inputSchema: SalarySlipInputSchema,
    outputSchema: SalarySlipOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
